# KEYWORDS

String, split, tuples, lists, dictionaries, formatting, datetime, date, timedelta, map function, lambda expressions, list comprehension.

# Keys and Values of the dictionary

In [104]:
name_email_dictionary = { 'ruslan':'ruslanmasinjila@gmail.com',
                          'hezron':'masinjila@un.org'
                        }

for name in name_email_dictionary:
    print(name_email_dictionary[name])

for email in name_email_dictionary.values():
    print(email)
    
for name, email in name_email_dictionary.items():
    print(name, email)

ruslanmasinjila@gmail.com
masinjila@un.org
ruslanmasinjila@gmail.com
masinjila@un.org
ruslan ruslanmasinjila@gmail.com
hezron masinjila@un.org


# String Formatting 

In [105]:
order = {
            'item_name': "milk",
            'packaging': 'carton',
            'item_price(USD)': 2.5,
            'quantity':  3,
            'date(dd/mm/yyyy)': "15/04/2021"
}

to_print = '{} of {} {}(s) was/were bought on {} at a price of {} USD each for a total of {} USD'

print(to_print.format(order['quantity'],
                      order['item_name'],
                      order['packaging'],
                      order['date(dd/mm/yyyy)'],
                      order['item_price(USD)'],
                      order['item_price(USD)']*order['quantity']
                      ))

3 of milk carton(s) was/were bought on 15/04/2021 at a price of 2.5 USD each for a total of 7.5 USD


# Dates and Times

In [106]:
import datetime as dt
import time as tm

now = tm.time()

dtnow = dt.datetime.fromtimestamp(now)

dtnow

datetime.datetime(2021, 4, 16, 21, 26, 15, 885854)

In [107]:
delta = dt.timedelta(days=100)

today = dt.date.today()

# Python Objects and Maps

In [108]:
class Person:
    department = "School of Information Technology and Engineering"
    
    def set_name(self, new_name):
        self.name = new_name
    
    def set_location(self, new_location):
        self.location = new_location

In [109]:
#for i in range(10000):
#    number = '{:04}'.format(i)
#    print(number)

# Map in Python

In [110]:
items1 = [1,5,3,7,9,2]
items2 = [9,5,7,3,6,8]

result = map(min,[items1,items2])

for i in result:
    print(i)


1
3


# Lambda Expressions and List Compressions

In [111]:
function = lambda a,b,c : a+b

In [112]:
lst = [1,2,3,4,5,6,7,8,9,10]

lst_normalized = [x/sum(lst) for x in lst]

print(lst_normalized)

# Using map and lambda

lst_normalized = map(lambda x: x/sum(lst),lst)

print(list(lst_normalized))

[0.01818181818181818, 0.03636363636363636, 0.05454545454545454, 0.07272727272727272, 0.09090909090909091, 0.10909090909090909, 0.12727272727272726, 0.14545454545454545, 0.16363636363636364, 0.18181818181818182]
[0.01818181818181818, 0.03636363636363636, 0.05454545454545454, 0.07272727272727272, 0.09090909090909091, 0.10909090909090909, 0.12727272727272726, 0.14545454545454545, 0.16363636363636364, 0.18181818181818182]


In [113]:
# Exercise


people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

# Normal Function
def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
# Using Lambda function with input
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
# Using map and lambda functions
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

In [114]:
# List compression using two variables

def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]

True

# Numpy (Numerical Python Library)

In [115]:
import numpy as np
import math

## Array Creation

In [116]:
# Create a numpy array by passing a list into it
a = np.array([1,2,3,4,5])
print(a)

# Find the dimension of the array using ndim
print(a.ndim)


# A multidimensional array from a list of lists

b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)


# Shape gives the leanth of each dimension
print(b.shape)


# Checking the type of the array
print(type(b))

# Checking the type of the elements of the array
print(b.dtype)

# Floats
c = np.array([2.2,2.3])
print(c.dtype)

# Create a numpy array of known shape filled with zeroes or ones
d = np.zeros((2,3))

# Create numpy array with random elements
e = np.random.rand(2,3)

# Create a numpy array specified by range and interval, excluding last number
d = np.arange(10,50,2)
print(d)

# Create numpy array with n floats between two numbers, inclusive.
f = np.linspace(0,2,15)
print(f)

[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]]
2
(2, 3)
<class 'numpy.ndarray'>
int64
float64
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143 1.57142857
 1.71428571 1.85714286 2.        ]


# Array Operations

In [117]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

# Element-wise operations
print(a-b)
print(a+b)
print(a*b)
print(a/b)

# Boolean Array
print(b%2==0)

# Matrix manipulation
# For dot product, use @ sign
print(a@b)


array1 = np.array([[1,2,3],[4,5,6]])
array2= np.array([[1.2,3.1,4.0],[9.1,8.4,6.7]])

print(array1)
print(array2)

array3 = array1+array2

print(array3)
print(array3.dtype)

print(array3.max())
print(array3.min())
print(array3.sum())
print(array3.min())



c = np.arange(1,16,1).reshape(3,5)
print(c)

# Sum along the columns
print(c.sum(axis=0))

# Sum along the rows
print(c.sum(axis=1))

[ 9 18 27 36]
[11 22 33 44]
[ 10  40  90 160]
[10. 10. 10. 10.]
[False  True False  True]
300
[[1 2 3]
 [4 5 6]]
[[1.2 3.1 4. ]
 [9.1 8.4 6.7]]
[[ 2.2  5.1  7. ]
 [13.1 13.4 12.7]]
float64
13.4
2.2
53.5
2.2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[18 21 24 27 30]
[15 40 65]
